# Generated by Django 3.0.5 on 2020-07-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0003_auto_20200723_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_detail',
            name='cust_age',
            field=models.IntegerField(null=True),
        ),
    ]
