# Generated by Django 3.0.5 on 2020-07-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0008_bank_detail_add_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_detail',
            name='dummy_add',
            field=models.CharField(default='', max_length=200),
        ),
    ]
