# Generated by Django 3.0.5 on 2020-07-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0009_bank_detail_dummy_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_detail',
            name='req_money',
            field=models.IntegerField(default=0),
        ),
    ]
